export default [
    "Kira does makeup",
    "Frames start dropping",
    "\"I'm a vegan\"",
    "Kira denies chat of MUBBLEZ",
    "\"Marxism is a critique of capitalism\"",
    "Chloe gets horny",
    "Spent the Rent dono bomb",
    "Raid of over 100 people appears",
    "Kira does an impression",
    "Kira slaps at a fly",
    "\"SHUT UUUUUP!!!\"",
    "Kira vapes some weed",
    "Star Trek is discussed",
    "\"What's the male version of Karen?\"",
    "Watch any part of a Richard Wolff video",
    "Kira yells at mods",
    "Kira coos about faces in chat",
    "\"Dareth\"",
    "Kira yells at groovers",
    "Alcohol on stream",
    "Kira can't think of a word",
    "Kira does Yoga",
    "Kira puts on glasses",
    "Scam sub goal ACTIVATE!",
    "Samba appears on stream",
    "Kira can't pronounce chatter name",
    "\"SOURCE?!\"",
    "Kira mentions bingo",
    "\"Why aren't you rich?\"",
    "Kira pauses video after SWEARING not to",
    "Kira doesn't thanks sub for 20+ mins",
    "Kira misidentifies an actor",
    "Male leftist streamer mentioned",
    "Paypig gifts a sub",
    "Sub goal met"
];
