export default [
    "Bunny does makeup",
    "Frames start dropping",
    "\"I'm a vegan\"",
    "Bunny denies chat of MUBBLEZ",
    "\"Marxism is a critique of capitalism\"",
    "Chloe gets horny",
    "Spent the Rent dono bomb",
    "Roomie hands bunny something",
    "Raid of over 100 people appears",
    "Bunny does an impression",
    "Bunny slaps at a fly",
    "\"SHUT UUUUUP!!!\"",
    "Bunny vapes some weed",
    "Star Trek is discussed",
    "Chatter says $5 a MONTH",
    "\"What's the male version of Karen?\"",
    "Watch any part of a Richard Wolff video",
    "Bunny yells at mods",
    "Breezy plugs her paypal",
    "Bunny coos about faces in chat",
    "\"Dareth\"",
    "Bunny yells at groovers",
    "Alcohol on stream",
    "Bunny can't think of a word",
    "Bunny does Yoga",
    "Bunny puts on glasses",
    "Scam sub goal ACTIVATE!",
    "Samba appears on stream",
    "Bunny can't pronounce chatter name",
    "\"SOURCE?!\"",
    "Bunny mentions bingo",
    "\"Why aren't you rich?\""
];